@startuml
title WarmHouse Devices Service Code Diagram

top to bottom direction

class Device {
  +String guid
  +String name
  +String type
  +Integer ownerId
  +DeviceState state
  +void register()
}

class DeviceState {
  +String stateName
  +Date changedAt
  +void changeState(string stateName)
}

class DevicesService {
  +void registerDevice()
  +void changeDeviceState()
}

class KafkaConsumer {
  +Settings settings
  +void consume()
}

Device "1" -- "1" DeviceState : has
KafkaConsumer -- Device : updates
DevicesService -- Device : register and updates

@enduml
